--
-- PostgreSQL database dump
--

\restrict HH8iA4Vtgpt9dPWUKR74bd2t7hORBiqh22BwqZjJcFEfNQzBH7UwFzLLyRn7R7Y

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public."BasketItem" DROP CONSTRAINT "FK_BasketItem_ShoppingCarts_ShoppingCartId";
DROP INDEX public."IX_BasketItem_ShoppingCartId";
ALTER TABLE ONLY public."__EFMigrationsHistory" DROP CONSTRAINT "PK___EFMigrationsHistory";
ALTER TABLE ONLY public."ShoppingCarts" DROP CONSTRAINT "PK_ShoppingCarts";
ALTER TABLE ONLY public."BasketItem" DROP CONSTRAINT "PK_BasketItem";
DROP TABLE public."__EFMigrationsHistory";
DROP TABLE public."ShoppingCarts";
DROP TABLE public."BasketItem";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: BasketItem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BasketItem" (
    "Id" integer NOT NULL,
    "ProductId" text NOT NULL,
    "ProductName" text NOT NULL,
    "Price" numeric NOT NULL,
    "Quantity" integer NOT NULL,
    "ShoppingCartId" integer NOT NULL,
    "OriginalPrice" numeric DEFAULT 0.0 NOT NULL,
    "ImageUrl" text
);


--
-- Name: BasketItem_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BasketItem" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BasketItem_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ShoppingCarts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ShoppingCarts" (
    "Id" integer NOT NULL,
    "UserName" text NOT NULL
);


--
-- Name: ShoppingCarts_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ShoppingCarts" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ShoppingCarts_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: BasketItem; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."BasketItem" ("Id", "ProductId", "ProductName", "Price", "Quantity", "ShoppingCartId", "OriginalPrice", "ImageUrl") FROM stdin;
1	111	Gaming Mouse	500	1	1	0.0	\N
134	0e4200aa-28c2-4ccd-b085-9d7bc30ecb8d	Monitor	4500	6	26	0.0	\N
135	a162ea0f-7c58-4a47-a8b6-d2d98fbdd3c9	Mechanical Keyboard	1200	9	26	0.0	\N
136	0e4200aa-28c2-4ccd-b085-9d7bc30ecb8d	Monitor	4500	6	25	0.0	\N
137	a162ea0f-7c58-4a47-a8b6-d2d98fbdd3c9	Mechanical Keyboard	1200	8	25	0.0	\N
218	bb00b766-2dd8-491d-b527-9776aa28fdc9	Monitor	1000	2	32	1000	/images/25f05eac-a1a7-4554-bae8-fbd04ddadeb3.jpg
224	bb00b766-2dd8-491d-b527-9776aa28fdc9	Monitor	1000	1	46	1000	/images/25f05eac-a1a7-4554-bae8-fbd04ddadeb3.jpg
227	4c443b0a-113d-4b82-8604-aad665ec99b3	Mekanik Klavye	3000	1	32	3000	/images/4d9eb791-d69a-43d5-ac89-3bec040267ec.jpg
\.


--
-- Data for Name: ShoppingCarts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ShoppingCarts" ("Id", "UserName") FROM stdin;
1	ahmet
32	guest-03cb7856
26	ahmetk
25	ahmetk
46	korayk2
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260316113422_InitialCreate	10.0.5
20260323090547_AddOriginalPriceToBasketItem	10.0.5
20260324100324_AddImageUrlToBasketItem	10.0.5
20260326103515_Initial	10.0.5
\.


--
-- Name: BasketItem_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."BasketItem_Id_seq"', 232, true);


--
-- Name: ShoppingCarts_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ShoppingCarts_Id_seq"', 51, true);


--
-- Name: BasketItem PK_BasketItem; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BasketItem"
    ADD CONSTRAINT "PK_BasketItem" PRIMARY KEY ("Id");


--
-- Name: ShoppingCarts PK_ShoppingCarts; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ShoppingCarts"
    ADD CONSTRAINT "PK_ShoppingCarts" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_BasketItem_ShoppingCartId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_BasketItem_ShoppingCartId" ON public."BasketItem" USING btree ("ShoppingCartId");


--
-- Name: BasketItem FK_BasketItem_ShoppingCarts_ShoppingCartId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BasketItem"
    ADD CONSTRAINT "FK_BasketItem_ShoppingCarts_ShoppingCartId" FOREIGN KEY ("ShoppingCartId") REFERENCES public."ShoppingCarts"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict HH8iA4Vtgpt9dPWUKR74bd2t7hORBiqh22BwqZjJcFEfNQzBH7UwFzLLyRn7R7Y

