--
-- PostgreSQL database dump
--

\restrict 6jCCLJkUKRRFoaUXme1vBjETUSj8pdmMrWXkTysSZddVujzvAvXu0AFmq8Jd3QU

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public."__EFMigrationsHistory" DROP CONSTRAINT "PK___EFMigrationsHistory";
ALTER TABLE ONLY public."Coupons" DROP CONSTRAINT "PK_Coupons";
DROP TABLE public."__EFMigrationsHistory";
DROP TABLE public."Coupons";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Coupons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Coupons" (
    "Id" integer NOT NULL,
    "ProductName" text NOT NULL,
    "Amount" integer NOT NULL,
    "Code" text DEFAULT ''::text NOT NULL,
    "Description" text DEFAULT ''::text NOT NULL,
    "IsActive" boolean DEFAULT false NOT NULL
);


--
-- Name: Coupons_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Coupons" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Coupons_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: Coupons; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Coupons" ("Id", "ProductName", "Amount", "Code", "Description", "IsActive") FROM stdin;
1		20	KEYF20	KEYF20 koduyla 20 lira indirim!	t
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260316101144_InitialCreate	10.0.5
20260324121437_UpdateCouponEntity	10.0.5
20260326103445_Initial	10.0.5
\.


--
-- Name: Coupons_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Coupons_Id_seq"', 1, true);


--
-- Name: Coupons PK_Coupons; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Coupons"
    ADD CONSTRAINT "PK_Coupons" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

\unrestrict 6jCCLJkUKRRFoaUXme1vBjETUSj8pdmMrWXkTysSZddVujzvAvXu0AFmq8Jd3QU

