--
-- PostgreSQL database dump
--

\restrict IkFJlguXi0DU8hHFAK5tejZhJBmvfwQ668AwK1FTqN2XR0pemdcVFXvzXUQU1Oe

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public."__EFMigrationsHistory" DROP CONSTRAINT "PK___EFMigrationsHistory";
ALTER TABLE ONLY public."AppUsers" DROP CONSTRAINT "PK_AppUsers";
DROP TABLE public."__EFMigrationsHistory";
DROP TABLE public."AppUsers";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AppUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AppUsers" (
    "Id" integer NOT NULL,
    "UserName" text NOT NULL,
    "Password" text NOT NULL,
    "Email" text NOT NULL,
    "Role" text DEFAULT ''::text NOT NULL
);


--
-- Name: AppUsers_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AppUsers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AppUsers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: AppUsers; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."AppUsers" ("Id", "UserName", "Password", "Email", "Role") FROM stdin;
1	ahmetk	1234	ahmetk@gmail.com	
2	ahmetkk	1234	ahmetk@gmail.com	
4	korayk	1234	korayk@gmail.com	User
6	merick	$2a$11$oiBwirnRUjiHObAYxdPTne1xHlYXc6gNsPWTgtfYXm.q5.GTgq2wq	merick@gmail.com	User
3	ahmetkoc	$2a$11$3seui67EqAjz3ZyqlH7TzO.p2XtL/du1Eq3JrVAVGERHbkMSy/cOK	ahmetkoc@gmail.com	Admin
7	korayk2	$2a$11$4VcpJjcjYliFgtPJOt8qPuZM2WH8YLvCp0RRROYoxr4BCWDSLNN56	korayk2@gmail.com	User
5	admin	a12IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi	admin@ecommerce.com	Admin
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260317071804_first	10.0.5
20260323122249_AddRoleToUser	10.0.5
20260326103521_Initial	10.0.5
\.


--
-- Name: AppUsers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AppUsers_Id_seq"', 7, true);


--
-- Name: AppUsers PK_AppUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AppUsers"
    ADD CONSTRAINT "PK_AppUsers" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

\unrestrict IkFJlguXi0DU8hHFAK5tejZhJBmvfwQ668AwK1FTqN2XR0pemdcVFXvzXUQU1Oe

