--
-- PostgreSQL database dump
--

\restrict VQxjeNQGzGVERNFi5CIZooael1A1vQ8l95f5Q5PukCMwM2ot1lVZ8C4nb0QVumA

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public."__EFMigrationsHistory" DROP CONSTRAINT "PK___EFMigrationsHistory";
ALTER TABLE ONLY public."Stocks" DROP CONSTRAINT "PK_Stocks";
DROP TABLE public."__EFMigrationsHistory";
DROP TABLE public."Stocks";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Stocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Stocks" (
    "Id" integer NOT NULL,
    "ProductId" text NOT NULL,
    "Quantity" integer NOT NULL,
    "ProductName" text DEFAULT ''::text NOT NULL
);


--
-- Name: Stocks_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Stocks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Stocks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: Stocks; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Stocks" ("Id", "ProductId", "Quantity", "ProductName") FROM stdin;
3	bb00b766-2dd8-491d-b527-9776aa28fdc9	4	Monitor
2	bb1dc241-c41a-4eae-85a3-b260b219f59c	8	Kasa
1	3a23dda3-0fb3-4b64-9d8a-928333aa7df4	19	Kulaklık
5	d06bf12d-1e8e-43ab-a5f7-ef227fae92a4	19	Mouse
4	4c443b0a-113d-4b82-8604-aad665ec99b3	28	Mekanik Klavye
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260318112205_InitialInventory	10.0.5
20260326101232_Initial	10.0.5
\.


--
-- Name: Stocks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Stocks_Id_seq"', 5, true);


--
-- Name: Stocks PK_Stocks; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Stocks"
    ADD CONSTRAINT "PK_Stocks" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

\unrestrict VQxjeNQGzGVERNFi5CIZooael1A1vQ8l95f5Q5PukCMwM2ot1lVZ8C4nb0QVumA

