--
-- PostgreSQL database dump
--

\restrict 8rSsS7PsRjWEz3hse4gOPaojwVEinLazT1xQImjoHNPXpLhUepmUbDHTpUPjWPJ

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public."OrderItems" DROP CONSTRAINT "FK_OrderItems_Orders_OrderId";
DROP INDEX public."IX_OrderItems_OrderId";
ALTER TABLE ONLY public."__EFMigrationsHistory" DROP CONSTRAINT "PK___EFMigrationsHistory";
ALTER TABLE ONLY public."Orders" DROP CONSTRAINT "PK_Orders";
ALTER TABLE ONLY public."OrderItems" DROP CONSTRAINT "PK_OrderItems";
DROP TABLE public."__EFMigrationsHistory";
DROP TABLE public."Orders";
DROP TABLE public."OrderItems";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: OrderItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."OrderItems" (
    "Id" integer NOT NULL,
    "ProductId" text NOT NULL,
    "ProductName" text NOT NULL,
    "Price" numeric NOT NULL,
    "Quantity" integer NOT NULL,
    "ImageUrl" text,
    "OrderId" integer NOT NULL
);


--
-- Name: OrderItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."OrderItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrderItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Orders" (
    "Id" integer NOT NULL,
    "UserName" text NOT NULL,
    "TotalPrice" numeric NOT NULL,
    "AddressLine" text NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "Status" integer NOT NULL,
    "CouponCode" text,
    "Discount" numeric NOT NULL,
    "TransactionId" text
);


--
-- Name: Orders_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Orders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: OrderItems; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."OrderItems" ("Id", "ProductId", "ProductName", "Price", "Quantity", "ImageUrl", "OrderId") FROM stdin;
1	3a23dda3-0fb3-4b64-9d8a-928333aa7df4	Kulaklık	2500	1	/images/84e996f6-e936-4ece-999d-20383897cb76.jpg	1
2	bb1dc241-c41a-4eae-85a3-b260b219f59c	Kasa	4000	1	/images/66a0bda8-7835-42a4-b15c-fe951f81c7b4.jpg	1
3	4c443b0a-113d-4b82-8604-aad665ec99b3	Mekanik Klavye	3000	2	/images/4d9eb791-d69a-43d5-ac89-3bec040267ec.jpg	2
4	d06bf12d-1e8e-43ab-a5f7-ef227fae92a4	Mouse	2000	1	/images/8f3f3ff1-ef93-4269-b7b8-601923bc20d2.jpg	3
5	3a23dda3-0fb3-4b64-9d8a-928333aa7df4	Kulaklık	2500	1	/images/84e996f6-e936-4ece-999d-20383897cb76.jpg	4
6	bb1dc241-c41a-4eae-85a3-b260b219f59c	Kasa	4000	1	/images/66a0bda8-7835-42a4-b15c-fe951f81c7b4.jpg	5
7	d06bf12d-1e8e-43ab-a5f7-ef227fae92a4	Mouse	2000	1	/images/8f3f3ff1-ef93-4269-b7b8-601923bc20d2.jpg	6
8	3a23dda3-0fb3-4b64-9d8a-928333aa7df4	Kulaklık	2500	3	/images/84e996f6-e936-4ece-999d-20383897cb76.jpg	7
9	bb1dc241-c41a-4eae-85a3-b260b219f59c	Kasa	4000	1	/images/66a0bda8-7835-42a4-b15c-fe951f81c7b4.jpg	8
10	bb00b766-2dd8-491d-b527-9776aa28fdc9	Monitor	1000	1	/images/25f05eac-a1a7-4554-bae8-fbd04ddadeb3.jpg	9
11	4c443b0a-113d-4b82-8604-aad665ec99b3	Mekanik Klavye	3000	1	/images/4d9eb791-d69a-43d5-ac89-3bec040267ec.jpg	10
12	bb1dc241-c41a-4eae-85a3-b260b219f59c	Kasa	4000	1	/images/66a0bda8-7835-42a4-b15c-fe951f81c7b4.jpg	11
13	3a23dda3-0fb3-4b64-9d8a-928333aa7df4	Kulaklık	2500	2	/images/84e996f6-e936-4ece-999d-20383897cb76.jpg	12
14	d06bf12d-1e8e-43ab-a5f7-ef227fae92a4	Mouse	2000	1	/images/8f3f3ff1-ef93-4269-b7b8-601923bc20d2.jpg	12
15	4c443b0a-113d-4b82-8604-aad665ec99b3	Mekanik Klavye	3000	1	/images/4d9eb791-d69a-43d5-ac89-3bec040267ec.jpg	13
\.


--
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Orders" ("Id", "UserName", "TotalPrice", "AddressLine", "CreatedDate", "Status", "CouponCode", "Discount", "TransactionId") FROM stdin;
1	ahmetkoc	6500	sgf	2026-03-25 11:47:10.881571+00	4	\N	0	fddad590-d962-4730-8d8d-7be31bf7565c
2	ahmetkoc	6000	adak sokak	2026-03-25 12:43:04.453539+00	0	\N	0	64b674cd-5b24-46a8-a403-de267393a96c
3	ahmetkoc	1980	sasa	2026-03-25 12:44:58.371152+00	0	KEYF20	20	aeed9ebe-3cf7-42bd-b040-0e4320d5feb2
4	ahmetkoc	2500	adad	2026-03-26 06:40:32.070094+00	0	\N	0	22ce4fc3-1cad-4705-87f3-b1d1aa63b563
5	ahmetkoc	4000	aba	2026-03-26 07:08:43.652219+00	0	\N	0	bc90fa41-5f45-4fff-aab0-e443344ed552
6	ahmetkoc	2000	adak sokak gazi	2026-03-26 09:51:37.284785+00	1	\N	0	66a58d5d-9007-4317-b01f-59da85fe16ba
7	ahmetkoc	7500	adak sokak gazi	2026-03-26 10:54:42.212394+00	3	\N	0	f8734ba6-528f-44dc-b0fb-75a257834fe5
8	ahmetkoc	4000	adak sokak gop	2026-03-26 11:25:29.344102+00	3	\N	0	bcc8d2c9-7732-4208-af25-c757c9665b6e
9	ahmetkoc	1000	adak sokak gop	2026-03-26 11:56:23.706071+00	2	\N	0	2b746fa5-c2f7-4c8f-abcf-b2bd1f80a99b
10	ahmetkoc	3000	gop ist	2026-03-27 09:43:29.53143+00	0	\N	0	6f3ef1b9-8b22-443c-a128-196cfa48b085
11	ahmetkoc	4000	asdsa	2026-03-30 11:46:17.524536+00	0	\N	0	30395496-8503-47d5-a0ca-5df8b6a4239d
12	ahmetkoc	7000	İstanbul/gop 	2026-04-10 07:15:00.345215+00	0	\N	0	e6b259c4-1036-468e-ab43-9dbd83cf6483
13	ahmetkoc	3000	İstanbul/gop 	2026-04-10 07:20:09.408601+00	0	\N	0	87844e8a-6c49-4b65-a085-5ce55d5cebbe
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
\.


--
-- Name: OrderItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."OrderItems_Id_seq"', 15, true);


--
-- Name: Orders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Orders_Id_seq"', 13, true);


--
-- Name: OrderItems PK_OrderItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "PK_OrderItems" PRIMARY KEY ("Id");


--
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_OrderItems_OrderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_OrderItems_OrderId" ON public."OrderItems" USING btree ("OrderId");


--
-- Name: OrderItems FK_OrderItems_Orders_OrderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."OrderItems"
    ADD CONSTRAINT "FK_OrderItems_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES public."Orders"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict 8rSsS7PsRjWEz3hse4gOPaojwVEinLazT1xQImjoHNPXpLhUepmUbDHTpUPjWPJ

