--
-- PostgreSQL database dump
--

\restrict mciZIbXFlVhZLC7ghEYE2OW5aNt6f6NSa0zNv2FOIH9ymbe2kFTI84MRycVSIgu

-- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public."__EFMigrationsHistory" DROP CONSTRAINT "PK___EFMigrationsHistory";
ALTER TABLE ONLY public."Transactions" DROP CONSTRAINT "PK_Transactions";
DROP TABLE public."__EFMigrationsHistory";
DROP TABLE public."Transactions";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Transactions" (
    "Id" integer NOT NULL,
    "CardNumber" text NOT NULL,
    "CardHolderName" text NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Status" text NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL,
    "TransactionId" text NOT NULL
);


--
-- Name: Transactions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Transactions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Transactions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: Transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."Transactions" ("Id", "CardNumber", "CardHolderName", "Amount", "Status", "TransactionDate", "TransactionId") FROM stdin;
1	2134****2456	dasada	4000.00	Success	2026-03-26 07:08:43.394052+00	bc90fa41-5f45-4fff-aab0-e443344ed552
2	2314****3213	asdasdasd	2000.00	Success	2026-03-26 09:51:37.120934+00	66a58d5d-9007-4317-b01f-59da85fe16ba
3	2324****4445	sasdasd	7500.00	Success	2026-03-26 10:54:41.924917+00	f8734ba6-528f-44dc-b0fb-75a257834fe5
4	2134****6454	asdsdas	4000.00	Success	2026-03-26 11:25:29.061094+00	bcc8d2c9-7732-4208-af25-c757c9665b6e
5	3425****5643	sadasdsa	1000.00	Success	2026-03-26 11:56:23.574547+00	2b746fa5-c2f7-4c8f-abcf-b2bd1f80a99b
6	2134****4321	ahmet	3000.00	Success	2026-03-27 09:43:29.2211+00	6f3ef1b9-8b22-443c-a128-196cfa48b085
7	1265****6543	sdffgh	4000.00	Success	2026-03-30 11:46:17.052243+00	30395496-8503-47d5-a0ca-5df8b6a4239d
8	3412****2343	ahmet koc	7000.00	Success	2026-04-10 07:15:00.090019+00	e6b259c4-1036-468e-ab43-9dbd83cf6483
9	2134****3245	asdas	3000.00	Success	2026-04-10 07:20:09.165311+00	87844e8a-6c49-4b65-a085-5ce55d5cebbe
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
\.


--
-- Name: Transactions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Transactions_Id_seq"', 9, true);


--
-- Name: Transactions PK_Transactions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Transactions"
    ADD CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

\unrestrict mciZIbXFlVhZLC7ghEYE2OW5aNt6f6NSa0zNv2FOIH9ymbe2kFTI84MRycVSIgu

