resources:
- messaging
- notification-api
- catalog-api
- discount-api
- identity-api
- basket-api
- payment-api
- order-api
- inventory-api
- gateway
- web-ui
- dashboard.yaml
- redis.yaml
- secrets.yaml

generatorOptions:
  disableNameSuffixHash: true


