apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: catalog-db
  spec:
    selector:
      matchLabels:
        app: catalog-db
    template:
      metadata:
        labels:
          app: catalog-db
      spec:
        containers:
        - name: postgres
          image: postgres:16
          env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: password123
          - name: POSTGRES_DB
            value: CatalogDb
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: catalog-db-data
            mountPath: /var/lib/postgresql
          - name: catalog-db-init-script
            mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
        volumes:
        - name: catalog-db-data
          persistentVolumeClaim:
            claimName: catalog-db-pvc
        - name: catalog-db-init-script
          configMap:
            name: catalog-db-init
- apiVersion: v1
  kind: Service
  metadata:
    name: catalog-db
  spec:
    selector:
      app: catalog-db
    ports:
    - port: 5432
      targetPort: 5432
# --- IDENTITY ---
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: identity-db
  spec:
    selector:
      matchLabels:
        app: identity-db
    template:
      metadata:
        labels:
          app: identity-db
      spec:
        containers:
        - name: postgres
          image: postgres:16
          env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: password123
          - name: POSTGRES_DB
            value: IdentityDb
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: identity-db-data
            mountPath: /var/lib/postgresql
          - name: identity-db-init-script
            mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
        volumes:
        - name: identity-db-data
          persistentVolumeClaim:
            claimName: identity-db-pvc
        - name: identity-db-init-script
          configMap:
            name: identity-db-init
- apiVersion: v1
  kind: Service
  metadata:
    name: identity-db
  spec:
    selector:
      app: identity-db
    ports:
    - port: 5432
      targetPort: 5432
# --- BASKET ---
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: basket-db
  spec:
    selector:
      matchLabels:
        app: basket-db
    template:
      metadata:
        labels:
          app: basket-db
      spec:
        containers:
        - name: postgres
          image: postgres:16
          env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: password123
          - name: POSTGRES_DB
            value: BasketDb
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: basket-db-data
            mountPath: /var/lib/postgresql
          - name: basket-db-init-script
            mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
        volumes:
        - name: basket-db-data
          persistentVolumeClaim:
            claimName: basket-db-pvc
        - name: basket-db-init-script
          configMap:
            name: basket-db-init
- apiVersion: v1
  kind: Service
  metadata:
    name: basket-db
  spec:
    selector:
      app: basket-db
    ports:
    - port: 5432
      targetPort: 5432
# --- DISCOUNT ---
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: discount-db
  spec:
    selector:
      matchLabels:
        app: discount-db
    template:
      metadata:
        labels:
          app: discount-db
      spec:
        containers:
        - name: postgres
          image: postgres:16
          env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: password123
          - name: POSTGRES_DB
            value: DiscountDb
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: discount-db-data
            mountPath: /var/lib/postgresql
          - name: discount-db-init-script
            mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
        volumes:
        - name: discount-db-data
          persistentVolumeClaim:
            claimName: discount-db-pvc
        - name: discount-db-init-script
          configMap:
            name: discount-db-init
- apiVersion: v1
  kind: Service
  metadata:
    name: discount-db
  spec:
    selector:
      app: discount-db
    ports:
    - port: 5432
      targetPort: 5432
# --- ORDER ---
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: order-db
  spec:
    selector:
      matchLabels:
        app: order-db
    template:
      metadata:
        labels:
          app: order-db
      spec:
        containers:
        - name: postgres
          image: postgres:16
          env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: password123
          - name: POSTGRES_DB
            value: OrderDb
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: order-db-data
            mountPath: /var/lib/postgresql
          - name: order-db-init-script
            mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
        volumes:
        - name: order-db-data
          persistentVolumeClaim:
            claimName: order-db-pvc
        - name: order-db-init-script
          configMap:
            name: order-db-init
- apiVersion: v1
  kind: Service
  metadata:
    name: order-db
  spec:
    selector:
      app: order-db
    ports:
    - port: 5432
      targetPort: 5432
# --- PAYMENT ---
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: payment-db
  spec:
    selector:
      matchLabels:
        app: payment-db
    template:
      metadata:
        labels:
          app: payment-db
      spec:
        containers:
        - name: postgres
          image: postgres:16
          env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: password123
          - name: POSTGRES_DB
            value: PaymentDb
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: payment-db-data
            mountPath: /var/lib/postgresql
          - name: payment-db-init-script
            mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
        volumes:
        - name: payment-db-data
          persistentVolumeClaim:
            claimName: payment-db-pvc
        - name: payment-db-init-script
          configMap:
            name: payment-db-init
- apiVersion: v1
  kind: Service
  metadata:
    name: payment-db
  spec:
    selector:
      app: payment-db
    ports:
    - port: 5432
      targetPort: 5432
# --- INVENTORY ---
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: inventory-db
  spec:
    selector:
      matchLabels:
        app: inventory-db
    template:
      metadata:
        labels:
          app: inventory-db
      spec:
        containers:
        - name: postgres
          image: postgres:16
          env:
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: password123
          - name: POSTGRES_DB
            value: InventoryDb
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: inventory-db-data
            mountPath: /var/lib/postgresql
          - name: inventory-db-init-script
            mountPath: /docker-entrypoint-initdb.d
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
        volumes:
        - name: inventory-db-data
          persistentVolumeClaim:
            claimName: inventory-db-pvc
        - name: inventory-db-init-script
          configMap:
            name: inventory-db-init
- apiVersion: v1
  kind: Service
  metadata:
    name: inventory-db
  spec:
    selector:
      app: inventory-db
    ports:
    - port: 5432
      targetPort: 5432
