---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
  labels:
    app: messaging
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: messaging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: messaging
    spec:
      containers:
      - name: messaging
        image: docker.io/library/rabbitmq:4.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics
            - -q
            - check_running
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - name: tcp
          containerPort: 5672
        envFrom:
        - configMapRef:
            name: messaging-env
      terminationGracePeriodSeconds: 180
